# Generated by Django 3.0.3 on 2020-02-19 15:33
import os

from django.conf import settings
from django.core.management import call_command
from django.db import migrations


def load_points(*args, **kwargs):
    fixture_path = os.path.join(settings.BASE_DIR, 'content', 'fixtures', 'initial.json')
    call_command('loaddata', fixture_path)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_points)
    ]
